"""
Django settings for gestion_conteneurs project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c8r#w$_cv&%+l*jhge=z!sj-7=i@h7ge)%-5-xm!0=vq@z0v+e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

# ALLOWED_HOSTS = ['empotage-oils-of-africa.net', 'www.empotage-oils-of-africa.net','gestion.empotage-oils-of-africa.net',]
ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'conteneurs.Personnel'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # par défaut
    'conteneurs.auth_backends.EmailOrUsernameModelBackend',  # notre backend personnalisé
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'conteneurs',
    'safedelete',
    'bootstrap4',
    'crispy_bootstrap4',
    'crispy_forms'
     
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_CLASS_CONVERTERS = {
    'file': 'form-control-file',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_conteneurs.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'app/templates'),
            os.path.join(BASE_DIR, 'etl/templates'),
            os.path.join(BASE_DIR, 'templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'gestion_conteneurs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'c2453269c_empotage',  # Nom de votre base de données
#         'HOST': '127.0.0.1',            # Adresse du serveur MySQL, ici localhost
#         'USER': 'c2453269c_admin',                 # Nom d'utilisateur MySQL
#         'PASSWORD': 'Maman+love123',                 # Mot de passe MySQL (à remplir si nécessaire)
#         'PORT': 3306,                   # Port MySQL, par défaut 3306
#         'OPTIONS': {
#             'sql_mode': 'STRICT_ALL_TABLES',  # Mode SQL strict pour respecter les bonnes pratiques
#         },
#     },
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

"""STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'conteneurs', 'static'),
]"""
MEDIA_URL = 'medias/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'medias')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
"""
LOGIN_URL = ""
LOGIN_REDIRECT_URL = ""
LOGOUT_REDIRECT_URL = """


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "/login/"
####  configuation SMTP

# settings.py
DEBUG=True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'empotageoilsofafrica@gmail.com'  # Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'vlym rhmk nmht rhge'

### MESSAGE D'ALERT

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

'''CSRF_TRUSTED_ORIGINS = [
    ""   
]'''

# settings.py
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
