# Generated by Django 5.1 on 2025-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0002_conteneur_numero_plomb2_conteneur_numero_plomb3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='numero_plomb4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='numero_plomb5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='photo_plomb4',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plomb4/'),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='photo_plomb5',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plomb5/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Personnel_pays',
            field=models.CharField(choices=[('côte_ivoire', 'côte_ivoire'), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Benin', 'Benin'), ('Gabon', 'Gabon')], default='côte_ivoire', max_length=20),
        ),
    ]
